name: tast_managger
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  dio: ^5.7.0
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
